import React from 'react';
import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from '@/lib/ui/toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children, modal}: Readonly<{children: React.ReactNode, modal: React.ReactNode}>) {
  return (
    <html lang="zh">
      <body>
        {modal}
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
