// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: et.go.proto

package et

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbTopic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Secret        *string                `protobuf:"bytes,3,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbTopic) Reset() {
	*x = PbTopic{}
	mi := &file_et_go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbTopic) ProtoMessage() {}

func (x *PbTopic) ProtoReflect() protoreflect.Message {
	mi := &file_et_go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbTopic.ProtoReflect.Descriptor instead.
func (*PbTopic) Descriptor() ([]byte, []int) {
	return file_et_go_proto_rawDescGZIP(), []int{0}
}

func (x *PbTopic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PbTopic) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *PbTopic) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

type PbSignalling struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sig:
	//
	//	*PbSignalling_Req
	//	*PbSignalling_Offer
	//	*PbSignalling_Answer
	//	*PbSignalling_IceCandidate
	Sig           isPbSignalling_Sig `protobuf_oneof:"sig"`
	Requester     string             `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
	Responder     *string            `protobuf:"bytes,6,opt,name=responder,proto3,oneof" json:"responder,omitempty"`
	Sender        *string            `protobuf:"bytes,7,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Receiver      *string            `protobuf:"bytes,8,opt,name=receiver,proto3,oneof" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbSignalling) Reset() {
	*x = PbSignalling{}
	mi := &file_et_go_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbSignalling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbSignalling) ProtoMessage() {}

func (x *PbSignalling) ProtoReflect() protoreflect.Message {
	mi := &file_et_go_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbSignalling.ProtoReflect.Descriptor instead.
func (*PbSignalling) Descriptor() ([]byte, []int) {
	return file_et_go_proto_rawDescGZIP(), []int{1}
}

func (x *PbSignalling) GetSig() isPbSignalling_Sig {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PbSignalling) GetReq() uint32 {
	if x != nil {
		if x, ok := x.Sig.(*PbSignalling_Req); ok {
			return x.Req
		}
	}
	return 0
}

func (x *PbSignalling) GetOffer() string {
	if x != nil {
		if x, ok := x.Sig.(*PbSignalling_Offer); ok {
			return x.Offer
		}
	}
	return ""
}

func (x *PbSignalling) GetAnswer() string {
	if x != nil {
		if x, ok := x.Sig.(*PbSignalling_Answer); ok {
			return x.Answer
		}
	}
	return ""
}

func (x *PbSignalling) GetIceCandidate() string {
	if x != nil {
		if x, ok := x.Sig.(*PbSignalling_IceCandidate); ok {
			return x.IceCandidate
		}
	}
	return ""
}

func (x *PbSignalling) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *PbSignalling) GetResponder() string {
	if x != nil && x.Responder != nil {
		return *x.Responder
	}
	return ""
}

func (x *PbSignalling) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *PbSignalling) GetReceiver() string {
	if x != nil && x.Receiver != nil {
		return *x.Receiver
	}
	return ""
}

type isPbSignalling_Sig interface {
	isPbSignalling_Sig()
}

type PbSignalling_Req struct {
	Req uint32 `protobuf:"varint,1,opt,name=req,proto3,oneof"`
}

type PbSignalling_Offer struct {
	Offer string `protobuf:"bytes,2,opt,name=offer,proto3,oneof"`
}

type PbSignalling_Answer struct {
	Answer string `protobuf:"bytes,3,opt,name=answer,proto3,oneof"`
}

type PbSignalling_IceCandidate struct {
	IceCandidate string `protobuf:"bytes,4,opt,name=iceCandidate,proto3,oneof"`
}

func (*PbSignalling_Req) isPbSignalling_Sig() {}

func (*PbSignalling_Offer) isPbSignalling_Sig() {}

func (*PbSignalling_Answer) isPbSignalling_Sig() {}

func (*PbSignalling_IceCandidate) isPbSignalling_Sig() {}

var File_et_go_proto protoreflect.FileDescriptor

var file_et_go_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x74, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x07, 0x50, 0x62, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x6b, 0x65, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22,
	0xa6, 0x02, 0x0a, 0x0c, 0x50, 0x62, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x12, 0x12, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x03, 0x72, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x06,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0c, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c,
	0x69, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x73,
	0x69, 0x67, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x65, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_et_go_proto_rawDescOnce sync.Once
	file_et_go_proto_rawDescData = file_et_go_proto_rawDesc
)

func file_et_go_proto_rawDescGZIP() []byte {
	file_et_go_proto_rawDescOnce.Do(func() {
		file_et_go_proto_rawDescData = protoimpl.X.CompressGZIP(file_et_go_proto_rawDescData)
	})
	return file_et_go_proto_rawDescData
}

var file_et_go_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_et_go_proto_goTypes = []any{
	(*PbTopic)(nil),      // 0: PbTopic
	(*PbSignalling)(nil), // 1: PbSignalling
}
var file_et_go_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_et_go_proto_init() }
func file_et_go_proto_init() {
	if File_et_go_proto != nil {
		return
	}
	file_et_go_proto_msgTypes[0].OneofWrappers = []any{}
	file_et_go_proto_msgTypes[1].OneofWrappers = []any{
		(*PbSignalling_Req)(nil),
		(*PbSignalling_Offer)(nil),
		(*PbSignalling_Answer)(nil),
		(*PbSignalling_IceCandidate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_et_go_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_et_go_proto_goTypes,
		DependencyIndexes: file_et_go_proto_depIdxs,
		MessageInfos:      file_et_go_proto_msgTypes,
	}.Build()
	File_et_go_proto = out.File
	file_et_go_proto_rawDesc = nil
	file_et_go_proto_goTypes = nil
	file_et_go_proto_depIdxs = nil
}
